spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: shishamo
    password:
  h2:
    console:
      enabled: true
flyway:
  enabled: true
  locations: db/postgres