spring:
  thymeleaf:
    mode: HTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/sample?useSSL=false
    schema: sample
    username: sampleUser
    password: samplePassword
  jackson:
      serialization:
        indent_output: true

flyway:
  enabled: false
  locations: db/sample

mybatis:
  mapper-locations: mybatis/sql/*.xml
